# Generated by Django 5.2.1 on 2025-05-27 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_reputation', models.FloatField()),
                ('style', models.CharField(max_length=100)),
                ('starting_price', models.FloatField()),
                ('final_price', models.FloatField()),
                ('painting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auctions.painting')),
            ],
        ),
    ]
